//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class amet
    {
        public amet()
        {
            this.Tootaja = new HashSet<Tootaja>();
        }
    
        public int ametId { get; set; }
        public string amet_Nimetus { get; set; }
    
        public virtual ICollection<Tootaja> Tootaja { get; set; }
    }
}
