//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModelContainer : DbContext
    {
        public DBModelContainer()
            : base("name=DBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<amet> ametSet { get; set; }
        public DbSet<Tootaja> TootajaSet { get; set; }
        public DbSet<Toograafik> ToograafikSet { get; set; }
        public DbSet<Tellimus> TellimusSet { get; set; }
        public DbSet<klient> klientSet { get; set; }
        public DbSet<broneerimine> broneerimineSet { get; set; }
        public DbSet<laud> laudSet { get; set; }
        public DbSet<TellimusToode> TellimusToodeSet { get; set; }
    }
}
