//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategooria
    {
        public kategooria()
        {
            this.Toode = new HashSet<Toode>();
        }
    
        public int kategooriaId { get; set; }
        public string nimi { get; set; }
    
        public virtual ICollection<Toode> Toode { get; set; }
    }
}
