//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        public klient()
        {
            this.Tellimus = new HashSet<Tellimus>();
            this.broneerimine = new HashSet<broneerimine>();
        }
    
        public int klientId { get; set; }
        public string nimi { get; set; }
    
        public virtual ICollection<Tellimus> Tellimus { get; set; }
        public virtual ICollection<broneerimine> broneerimine { get; set; }
    }
}
