//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class laud
    {
        public laud()
        {
            this.broneerimine = new HashSet<broneerimine>();
        }
    
        public int laudId { get; set; }
        public string laud_number { get; set; }
        public string kohtade_arv { get; set; }
    
        public virtual ICollection<broneerimine> broneerimine { get; set; }
    }
}
