//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class makse
    {
        public int makseId { get; set; }
        public string kuupaev { get; set; }
        public string summa { get; set; }
        public string makseviis { get; set; }
    
        public virtual Tellimus Tellimus { get; set; }
    }
}
