//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarnija
    {
        public Tarnija()
        {
            this.Tooraine = new HashSet<Tooraine>();
        }
    
        public int TaarnijaId { get; set; }
        public string nimi { get; set; }
    
        public virtual ICollection<Tooraine> Tooraine { get; set; }
    }
}
