//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tellimus
    {
        public Tellimus()
        {
            this.TellimusToode = new HashSet<TellimusToode>();
        }
    
        public int TellimusId { get; set; }
        public string kuupaev { get; set; }
        public string kellaeg { get; set; }
    
        public virtual Tootaja Tootaja { get; set; }
        public virtual klient klient { get; set; }
        public virtual ICollection<TellimusToode> TellimusToode { get; set; }
    }
}
