//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toode
    {
        public Toode()
        {
            this.TellimusToode = new HashSet<TellimusToode>();
            this.TooteKoostisosa = new HashSet<TooteKoostisosa>();
        }
    
        public int ToodeId { get; set; }
        public string Nimetus { get; set; }
        public string kirjeldus { get; set; }
        public string hind { get; set; }
    
        public virtual ICollection<TellimusToode> TellimusToode { get; set; }
        public virtual kategooria kategooria { get; set; }
        public virtual ICollection<TooteKoostisosa> TooteKoostisosa { get; set; }
    }
}
