//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toograafik
    {
        public int ToograafikId { get; set; }
        public string kuupaev { get; set; }
    
        public virtual Tootaja Tootaja { get; set; }
    }
}
