//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tooraine
    {
        public int TooraineId { get; set; }
        public string nimi { get; set; }
        public string kogus { get; set; }
        public string hind { get; set; }
    
        public virtual Tarnija Tarnija { get; set; }
    }
}
