//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tootaja
    {
        public Tootaja()
        {
            this.Toograafik = new HashSet<Toograafik>();
            this.Tellimus = new HashSet<Tellimus>();
        }
    
        public int TootajaId { get; set; }
        public string nimi { get; set; }
    
        public virtual amet amet { get; set; }
        public virtual ICollection<Toograafik> Toograafik { get; set; }
        public virtual ICollection<Tellimus> Tellimus { get; set; }
    }
}
