//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KohvikModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TooteKoostisosa
    {
        public TooteKoostisosa()
        {
            this.Tellimus = new HashSet<Tellimus>();
        }
    
        public int tooteKoostisosaId { get; set; }
        public string kogus { get; set; }
    
        public virtual ICollection<Tellimus> Tellimus { get; set; }
        public virtual Toode Toode { get; set; }
        public virtual Koostisosa Koostisosa { get; set; }
    }
}
